export { default as Navbar } from "./Navbar";
export { default as Intro } from "./Intro";
export { default as About } from "./About";
export { default as Services } from "./Services";
export { default as Portifolio } from "./Portifolio";
export { default as Testimonials } from "./Testimonials";
export { default as Action } from "./Action";
export { default as Contact } from "./Contact";
export { default as SocialMedia } from "./SocialMedia";
